/*
 * This Java source file was generated by the Gradle 'init' task.
 */

public class App {
    public static void main(String[] args) {
        {
            GrosseZahl a = new GrosseZahl(12345);
            GrosseZahl b = new GrosseZahl("12345");
            GrosseZahl c = new GrosseZahl("12345678900987654321");
            System.out.println("a = " + a);
            System.out.println("b = " + b);
            System.out.println("c = " + c);
        }

        {
            GrosseZahl a = new GrosseZahl(12345);
            GrosseZahl b = new GrosseZahl("12345");
            System.out.println(a + " == " + b + " = " + (a.equal(b)));
            System.out.println(a + " < " + b + " = " + (a.less(b)));
            System.out.println(a + " > " + b + " = " + (a.greater(b)));
            System.out.println(a + " + " + b + " = " + (a.add(b)));
            System.out.println(b + " + " + a + " = " + (b.add(a)));
            System.out.println(a + " * " + b + " = " + (a.mult(b)));
            System.out.println(b + " * " + a + " = " + (b.mult(a)));
        }

        {
            GrosseZahl a = new GrosseZahl(12344);
            GrosseZahl b = new GrosseZahl("12335");
            System.out.println(a + " == " + b + " = " + (a.equal(b)));
            System.out.println(a + " < " + b + " = " + (a.less(b)));
            System.out.println(a + " > " + b + " = " + (a.greater(b)));
            System.out.println(a + " + " + b + " = " + (a.add(b)));
            System.out.println(b + " + " + a + " = " + (b.add(a)));
            System.out.println(a + " * " + b + " = " + (a.mult(b)));
            System.out.println(b + " * " + a + " = " + (b.mult(a)));
        }

        {
            GrosseZahl a = new GrosseZahl(123456);
            GrosseZahl b = new GrosseZahl("12335");
            System.out.println(a + " == " + b + " = " + (a.equal(b)));
            System.out.println(a + " < " + b + " = " + (a.less(b)));
            System.out.println(a + " > " + b + " = " + (a.greater(b)));
            System.out.println(a + " + " + b + " = " + (a.add(b)));
            System.out.println(b + " + " + a + " = " + (b.add(a)));
            System.out.println(a + " * " + b + " = " + (a.mult(b)));
            System.out.println(b + " * " + a + " = " + (b.mult(a)));
        }

        {
            GrosseZahl a = new GrosseZahl(54321);
            GrosseZahl b = new GrosseZahl("54321");
            System.out.println(a + " == " + b + " = " + (a.equal(b)));
            System.out.println(a + " < " + b + " = " + (a.less(b)));
            System.out.println(a + " > " + b + " = " + (a.greater(b)));
            System.out.println(a + " + " + b + " = " + (a.add(b)));
            System.out.println(b + " + " + a + " = " + (b.add(a)));
            System.out.println(a + " * " + b + " = " + (a.mult(b)));
            System.out.println(b + " * " + a + " = " + (b.mult(a)));
        }
    }
}
